[project]
name = 'marimograd'
version = "0.0.0"
description = "Export marimo notebooks in style"
# Please add authors and correct the email...
authors = [{name='tschm', email= 'tschm@mailinator.com'}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fire>=0.7.0",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
]

[project.urls]
repository = "https://github.com/tschm/marimograd"

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [
    "*__init__.py"
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Entry points for command-line scripts
[project.scripts]
marimograd = "export:cli"

[tool.hatch.build.targets.wheel]
packages = ["src/marimograd"]

[tool.hatch.build]
include = [
    "LICENSE",    # Ensure the LICENSE file is included in your package
    "README.md",
    "src/marimograd"
]

